from __future__ import annotations

from typing import Any

from sqlalchemy.orm import Session

from app.db.models import ModelTool


def build_tooluniverse_model_config(
    name: str,
    description: str,
    provider: str,
    endpoint_url: str | None,
    api_key_env_var: str | None,
    input_schema: dict[str, Any],
    output_schema: dict[str, Any],
) -> dict[str, Any]:
    return {
        "name": name,
        "description": description,
        "type": "CustomModelTool",
        "label": ["Model", "Custom", provider],
        "parameter": input_schema,
        "returns": output_schema,
        "provider": provider,
        "endpoint_url": endpoint_url,
        "api_key_env_var": api_key_env_var,
        "notes": "Generated by BioAutoScientist for ToolUniverse-style model onboarding.",
    }


def register_model_tool(
    db: Session,
    *,
    name: str,
    description: str,
    provider: str,
    endpoint_url: str | None,
    api_key_env_var: str | None,
    input_schema: dict[str, Any] | None,
    output_schema: dict[str, Any] | None,
) -> ModelTool:
    normalized_input_schema = input_schema or {
        "type": "object",
        "required": ["prompt"],
        "properties": {"prompt": {"type": "string"}},
    }
    normalized_output_schema = output_schema or {
        "type": "object",
        "properties": {"response": {"type": "string"}},
    }
    tooluniverse_config = build_tooluniverse_model_config(
        name=name,
        description=description,
        provider=provider,
        endpoint_url=endpoint_url,
        api_key_env_var=api_key_env_var,
        input_schema=normalized_input_schema,
        output_schema=normalized_output_schema,
    )
    existing = db.query(ModelTool).filter(ModelTool.name == name).first()
    if existing is None:
        model_tool = ModelTool(
            name=name,
            description=description,
            provider=provider,
            endpoint_url=endpoint_url,
            api_key_env_var=api_key_env_var,
            input_schema_json=normalized_input_schema,
            output_schema_json=normalized_output_schema,
            tooluniverse_config_json=tooluniverse_config,
            status="registered",
        )
        db.add(model_tool)
    else:
        model_tool = existing
        model_tool.description = description
        model_tool.provider = provider
        model_tool.endpoint_url = endpoint_url
        model_tool.api_key_env_var = api_key_env_var
        model_tool.input_schema_json = normalized_input_schema
        model_tool.output_schema_json = normalized_output_schema
        model_tool.tooluniverse_config_json = tooluniverse_config
        model_tool.status = "registered"
    db.commit()
    db.refresh(model_tool)
    return model_tool


def serialize_model_tool(model_tool: ModelTool) -> dict[str, Any]:
    return {
        "id": model_tool.id,
        "name": model_tool.name,
        "description": model_tool.description,
        "provider": model_tool.provider,
        "endpoint_url": model_tool.endpoint_url,
        "api_key_env_var": model_tool.api_key_env_var,
        "input_schema": model_tool.input_schema_json,
        "output_schema": model_tool.output_schema_json,
        "tooluniverse_config": model_tool.tooluniverse_config_json,
        "status": model_tool.status,
        "created_at": model_tool.created_at.isoformat(),
    }

